[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:frankenphp]
command=frankenphp run --config /etc/frankenphp/Caddyfile
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:queue]
process_name=%(program_name)s_%(process_num)02d
command=php /app/artisan queue:listen --sleep=3 --tries=3 --backoff=3 -v
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stopwaitsecs=3600

[program:scheduler]
process_name=%(program_name)s
command=sh -c "while true; do (cd /app && php artisan schedule:run >> /dev/null 2>&1); sleep 60; done"
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0